

GET  http://localhost:3001/api/accounts/
###

POST  http://localhost:3001/api/accounts/login
Content-Type: application/json

{
  "email":"123@example",
  "password":"123@"
}
###
DELETE    http://localhost:3001/api/accounts/64650d6163615c5820904cf8

###
POST http://localhost:3001/api/accounts/register
Content-Type: application/json

{
  "username": "Instructor Test",
  "email":"123@example",
  "password":"123@"
}
###
{
  "username": "Heart Beat Yoga",
  "email":"heartbeat.yoga.group@gmail.com",
  "password":"admin@yogaheartbeat999"
}
###


###



