export const fakeBookings = [
  {
    id: 1,
    userName: "John Doe",
    email: "johndoe@gmail.com",
    bookingDate: "10/06/23",
    status: 10,
    isMember: false,
  },
  {
    id: 2,
    userName: "Jane Smith",
    email: "janesmith@example.com",
    bookingDate: "12/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 3,
    userName: "Bob Johnson",
    email: "bobjohnson@example.com",
    bookingDate: "15/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 4,
    userName: "Alice Brown",
    email: "alicebrown@example.com",
    bookingDate: "20/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 5,
    userName: "Group Booking",
    email: "groupbooking@example.com",
    bookingDate: "25/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 6,
    userName: "Harry White",
    email: "harrywhite@example.com",
    bookingDate: "18/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 7,
    userName: "Emily Jones",
    email: "emilyjones@example.com",
    bookingDate: "22/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 8,
    userName: "David Green",
    email: "davidgreen@example.com",
    bookingDate: "08/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 9,
    userName: "David Green",
    email: "davidgreen@example.com",
    bookingDate: "08/06/23",
    status: 5,
    isMember: false,
  },
  {
    id: 10,
    userName: "Long-term Stay",
    email: "longtermstay@example.com",
    bookingDate: "01/07/23",
    status: 5,
    isMember: false,
  },
];
